api_gps_reporting:
    resource: "@ApiGpsReportingBundle/Resources/config/routing.yml"
    prefix:   /

api_gps_administration:
    resource: "@ApiGpsAdministrationBundle/Resources/config/routing.yml"
    prefix:   /

api_gps_espace_user:
    resource: "@ApiGpsEspaceUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#Company_rest
company:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/CompanyController.php"
    prefix:   /api

#user_rest
user:
    type:     rest
    resource: "@ApiGpsEspaceUserBundle/Controller/UserController.php"
    prefix:   /api

#Session_rest
session:
    type:     rest
    resource: "@ApiGpsEspaceUserBundle/Controller/SessionController.php"
    prefix:   /
#trafic_rest
traffic:
    type:     rest
    resource: "@ApiGpsReportingBundle/Controller/TraficController.php"
    prefix:   /api
#Vehicle_rest
vehicle:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/VehicleController.php"
    prefix:   /api

#Vehicle_rest
Reclam:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/ReclamController.php"
    prefix:   /api

#Box_rest
box:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/BoxController.php"
    prefix:   /api
#Trame_rest
trame:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/TrameController.php"
    prefix:   /api

#Driver_rest
driver:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/DriverController.php"
    prefix:   /api

#fleet_rest
fleet:
    type:     rest
    resource: "@ApiGpsAdministrationBundle/Controller/FleetController.php"
    prefix:   /api