security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_OPERATEUR:   ROLE_OPERATEUR
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_REVENDEUR:   ROLE_REVENDEUR
        ROLE_CREVENDEUR:  ROLE_CREVENDEUR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/api                              # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                           # Anonymous access is not allowed
            anonymous: false